In [1]:
import pandas as pd

In [2]:
df_all = pd.read_csv('../core/data/FanGraphsLeagueAverages.csv')

In [4]:
df_al = pd.read_csv('../core/data/al_pa.csv')
df_nl = pd.read_csv('../core/data/nl_pa.csv')

In [5]:
df_al = df_al['PA']
df_nl = df_nl['PA']

In [7]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Season  100 non-null    int64
 1   PA      100 non-null    int64
 2   BB%     100 non-null    object
 3   K%      100 non-null    object
 4   BB/K    100 non-null    float64
 5   AVG     100 non-null    float64
 6   OBP     100 non-null    float64
 7   SLG     100 non-null    float64
 8   OPS     100 non-null    float64
 9   ISO     100 non-null    float64
 10  Spd     100 non-null    float64
 11  BABIP   100 non-null    float64
 12  UBR     100 non-null    float64
 13  wGDP    100 non-null    float64
 14  wSB     100 non-null    float64
 15  wRC     100 non-null    int64
 16  wRC_NL  100 non-null    int64
 17  wRC_AL  100 non-null    int64
 18  wRAA    100 non-null    float64
 19  wOBA    100 non-null    float64
 20  wRC+    100 non-null    int64
dtypes: float64(13), int64(6), object(2)
memory usage: 16.5+ KB

In [9]:
df_all.insert(loc=2, column='PA_AL', value=df_al)
df_all.insert(loc=2, column='PA_NL', value=df_nl)

In [10]:
df_all

,Season,PA,PA_NL,PA_AL,BB%,K%,BB/K,AVG,OBP,SLG,...,BABIP,UBR,wGDP,wSB,wRC,wRC_NL,wRC_AL,wRAA,wOBA,wRC+
0,1919,76495,37731,38764,7.3 %,7.0 %,1.05,0.270,0.330,0.359,...,0.288,0.0,0.0,21.1,8379,3829,4550,477.1,0.331,100
1,1920,86011,42678,43333,7.4 %,6.5 %,1.14,0.284,0.343,0.384,...,0.300,0.0,0.0,-14.3,10368,4709,5659,580.0,0.344,100
2,1921,87139,42896,44243,7.4 %,6.2 %,1.20,0.299,0.357,0.416,...,0.313,0.0,0.0,-11.2,11556,5446,6110,680.8,0.357,100
3,1922,87886,44078,43808,7.9 %,6.0 %,1.30,0.297,0.359,0.415,...,0.309,0.0,0.0,-11.2,11772,5957,5815,751.3,0.359,100
4,1923,87719,43855,43864,8.2 %,6.2 %,1.31,0.292,0.356,0.405,...,0.305,0.0,0.0,-10.0,11509,5712,5797,675.6,0.357,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2014,178409,86575,91834,7.8 %,19.9 %,0.39,0.255,0.318,0.393,...,0.301,0.3,0.1,2.4,19818,9721,10097,639.1,0.315,100
96,2015,178221,86736,91485,7.8 %,19.9 %,0.39,0.258,0.321,0.412,...,0.301,-0.1,-0.6,1.7,20705,10112,10593,655.3,0.318,100
97,2016,179218,87546,91672,8.3 %,20.6 %,0.40,0.259,0.326,0.425,...,0.302,0.3,-0.4,1.3,21791,10783,11008,678.6,0.323,100
98,2017,180018,87753,92265,8.7 %,21.2 %,0.41,0.259,0.329,0.433,...,0.301,0.6,-1.1,1.2,22667,11282,11385,722.8,0.326,100
99,2018,180004,88080,91924,8.6 %,21.7 %,0.40,0.252,0.323,0.417,...,0.297,1.0,0.0,0.0,21752,10757,10995,709.5,0.320,100