In [37]:
import pandas as pd

In [42]:
catchers = pd.read_csv('../core/output/catchers.csv').reset_index()
fielders = pd.read_csv('../core/output/fielders.csv').reset_index()
pitchers = pd.read_csv('../core/output/pitchers.csv').reset_index()

In [40]:
catchers.reset_index(inplace=True)
fielders.reset_index(inplace=True)
pitchers.reset_index(inplace=True)

AttributeError: 'NoneType' object has no attribute 'reset_index'

In [43]:
catchers

,index,retroID,GS,InnOuts,PO,A,E,DP,PB,WP,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,NL
0,0,adamb105,1,27,6,0,0,0,0,0,...,0,0.0,0,5,0,0,0,0,0,0
1,1,adamb106,0,0,249,90,12,15,7,0,...,4,2.0,6,27,0,0,3,0,0,1
2,2,adamd101,3,78,9,2,0,0,1,0,...,0,0.0,1,3,0,0,0,0,1,0
3,3,adled101,65,1840,453,26,4,2,8,19,...,0,0.0,18,80,5,2,2,1,9,1
4,4,afent001,20,613,123,5,1,3,6,0,...,0,0.0,5,32,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1524,1524,zimmd101,27,744,150,18,6,1,5,12,...,45,25.0,246,678,27,13,37,14,99,1
1525,1525,zimmj101,298,8560,2131,150,21,26,19,84,...,1,2.0,78,154,12,11,31,4,38,1
1526,1526,zinta001,0,3,2,0,0,0,0,0,...,0,0.0,5,34,0,0,0,1,0,1
1527,1527,zunim001,535,14489,4356,264,21,22,39,0,...,2,4.0,138,714,1,45,8,11,38,0
1528,1528,zupof101,1,114,31,1,2,0,1,1,...,0,0.0,2,6,0,0,0,0,0,0

In [21]:
catchers_dict = catchers.set_index('index').to_dict()['retroID']
fielders_dict = fielders.set_index('index').to_dict()['retroID']
pitchers_dict = pitchers.set_index('index').to_dict()['retroID']
players_dict = {
    'C': catchers_dict,
    '1B': fielders_dict,
    '2B': fielders_dict,
    'SS': fielders_dict,
    '3B': fielders_dict,
    'OF': fielders_dict,
    'P': pitchers_dict
}

In [22]:
def get_catcher(catcher_id):
    return catchers_dict[catcher_id] if catchers_dict[catcher_id] is not None else ''

In [23]:
def get_fielder(fielder_id):
    return fielders_dict[fielder_id] if fielders_dict[fielder_id] is not None else ''

In [24]:
def get_pitcher(pitcher_id):
    return pitchers_dict[pitcher_id] if pitchers_dict[pitcher_id] is not None else ''

In [28]:
def get_player(player_id, position):
    return players_dict[position][player_id]